// Sentence-driven data loader.
// Source: sentences.json (generated by scripts/build_sentences.py).
// Each sentence = atomic composition with own audio + word timestamps.

import sentencesJson from "./sentences.json";

export type Phase = "HOOK" | "PROBLEM" | "AGITATE" | "SOLVE" | "ACTION";

export interface EnumBeat {
  item: string;
  frame: number;  // frame relative to sentence start (30fps)
  time: number;   // seconds relative to sentence start
}

export interface WordTimestamp {
  word: string;
  start: number; // seconds relative to sentence start
  end: number;
}

export interface Sentence {
  id: string;
  phase: Phase;
  display: string;
  tts: string;
  main_idea: string;
  enum_items: string[] | null;
  enum_beats: EnumBeat[] | null;
  pause_before_ms: number;
  pause_after_ms: number;
  speed: number;
  duration_s: number;
  visual_tail_ms?: number;  // thêm f visual (không audio) sau khi audio kết thúc
  cut_start_abs: number;
  cut_end_abs: number;
  word_timestamps: WordTimestamp[];
}

// Old PASA section start frames (monolithic timeline, for offset computation)
export const PHASE_START_FRAME: Record<Phase, number> = {
  HOOK: 0,
  PROBLEM: 500,
  AGITATE: 1050,
  SOLVE: 1770,
  ACTION: 2295,
};

const FPS = 30;

export const SENTENCES: Sentence[] = sentencesJson.sentences as Sentence[];

export function getSentence(id: string): Sentence {
  const s = SENTENCES.find((x) => x.id === id);
  if (!s) throw new Error(`Sentence not found: ${id}`);
  return s;
}

/** Frame offset into the old scene when the sentence composition starts at its frame 0. */
export function sceneOffsetFrame(s: Sentence): number {
  const globalFrameStart = Math.round(s.cut_start_abs * FPS);
  return globalFrameStart - PHASE_START_FRAME[s.phase];
}

/** Total frames = ceil((duration_s + visual_tail) × 30). */
export function durationFrames(s: Sentence): number {
  const tailS = (s.visual_tail_ms ?? 0) / 1000;
  return Math.ceil((s.duration_s + tailS) * FPS);
}
